-- Migration: Add new columns to tenants table for enhanced setup

ALTER TABLE tenants ADD COLUMN IF NOT EXISTS website_url VARCHAR(500);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS state VARCHAR(100);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS country VARCHAR(100);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS postal_code VARCHAR(20);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS timezone VARCHAR(100);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS business_hours JSONB;
